#!/bin/sh
#
# shinken-scheduler - Startup script for the Shinken Scheduler Daemon
#
# chkconfig: 2345 20 80
# description:  Shinken is a monitoring tool and the Scheduler \
#               is one of its daemon. This one get configuration \
#		from the arbiter His purpose is only to schedule \
#		do the checks and actions specified in the \
#		configuration received from the arbiter. 

### BEGIN INIT INFO
# Provides:          shinken-scheduler
# Required-Start:    $all 
# Required-Stop:     $all
# Should-Start:    
# Should-Stop: 
# Default-Start:     2 3 4 5 
# Default-Stop:      0 1 6
# Short-Description: Shinken scheduler daemon
# Description:       Shinken is a monitoring tool and the Scheduler
#                    is one of its daemon. This one get configuration from the arbiter
#                    His purpose is only to schedule do the checks and actions specified
#                    in the configuration received from the arbiter
### END INIT INFO



# Source function library.
. /etc/rc.d/init.d/functions


daemon_args="-d -c /etc/shinken/schedulerd.ini"             # Arguments to run the daemon with
pidfile=/var/run/shinken/schedulerd.pid

user=nagios
group=root

exec="/usr/sbin/shinken-scheduler"
prog=$(basename $exec)

[ -e /etc/sysconfig/$prog ] && . /etc/sysconfig/$prog

lockfile=/var/lock/subsys/$prog

start() {

    directory=$(dirname $pidfile)                                                                                                                                    
    [ ! -d $directory ] && mkdir -p $directory
    chown $user:$group $directory

    echo -n $"Starting $prog: "
    $exec $daemon_args
    # if not running, start it up here, usually something like "daemon $exec"
    retval=$?
    echo
    [ $retval -eq 0 ] && touch $lockfile
    return $retval
}

stop() {
    echo -n $"Stopping $prog: "
    killproc -p ${pidfile}
    # stop it here, often "killproc $prog"
    retval=$?
    echo
    [ $retval -eq 0 ] && rm -f $lockfile
    return $retval
}

restart() {
    stop
    start
}

case "$1" in
    start|stop|restart)
        $1
        ;;
    force-reload)
        restart
        ;;
    status)
        status -p $pidfile $prog
        ;;
    try-restart|condrestart)
        if status $prog >/dev/null ; then
            restart
        fi
	;;
    reload)
        # If config can be reloaded without restarting, implement it here,
        # remove the "exit", and add "reload" to the usage message below.
        # For example:
        # status $prog >/dev/null || exit 7
        # killproc $prog -HUP
        action $"Service ${0##*/} does not support the reload action: " /bin/false
        exit 3
        ;;
    *)
        echo $"Usage: $0 {start|stop|status|restart|try-restart|force-reload}"
        exit 2
esac
