#!/bin/bash
#Copyright (C) 2009-2010 :
#    Gabes Jean, naparuba@gmail.com
#    Gerhard Lausser, Gerhard.Lausser@consol.de
#
#This file is part of Shinken.
#
#Shinken is free software: you can redistribute it and/or modify
#it under the terms of the GNU Affero General Public License as published by
#the Free Software Foundation, either version 3 of the License, or
#(at your option) any later version.
#
#Shinken is distributed in the hope that it will be useful,
#but WITHOUT ANY WARRANTY; without even the implied warranty of
#MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#GNU Affero General Public License for more details.
#
#You should have received a copy of the GNU Affero General Public License
#along with Shinken.  If not, see <http://www.gnu.org/licenses/>.

TESTLIST=$1
COVERAGE=$2
PYLINT=$2
TESTLIST=$(readlink -f $TESTLIST)
test "$COVERAGE" == "COVERAGE" || COVERAGE="NOCOVERAGE"
test "$PYLINT" == "PYLINT" || PYLINT="NOPYLINT"

DIR=$(cd $(dirname "$0"); pwd)
cd ${DIR}/..
echo `pwd`

# Cleanup leftover files from former runs
rm -f nosetests.xml
test $COVERAGE == "COVERAGE" && rm -f coverage.xml
test $COVERAGE == "COVERAGE" && rm -f .coverage

function launch_and_assert {
    SCRIPT=$1
    if test $COVERAGE == "NOCOVERAGE"; then
      nosetests -v -s --with-xunit ./$SCRIPT
    else
      nosetests -v -s --with-xunit --with-coverage ./$SCRIPT
    fi
    if [ $? != 0 ]
	then
	echo "Error : the test $SCRIPT failed"
	exit 2
    fi
}

while read tfile
do
  case ${tfile:0:1} in
  "#") 
       ;;
  *)   launch_and_assert $tfile
       ;;
  esac
done < $TESTLIST

# Create the coverage file
test $COVERAGE == "COVERAGE" && coverage xml --omit=/usr/lib
