%rebase layout globals(), css=['system/css/log.css'], title='Architecture state', menu_part='/system'

%from shinken.bin import VERSION
%helper = app.helper
 <div class="alert alert-error alert-block span11">
    <a class="close" data-dismiss="alert" href="#">×</a>
    <h4 class="alert-heading">Warning!</h4>
    No Live Data
 </div>

<!-- Log Contaier START -->
<h2>System logs</h2>
<div class="pagination pull-right">
    <ul>
        <li><a href="#">Prev</a></li>
        <li class="active"><a href="#">1</a></li>
        <li><a href="#">2</a></li>
        <li><a href="#">3</a></li>
        <li><a href="#">4</a></li>
        <li><a href="#">Next</a></li>
    </ul>
</div>

<div id="log_container" class="tabbable tabs-left leftmargin span12">
    <ul class="nav nav-tabs span2">
        <li class="active"><a data-toggle="tab" href="#lA">Week 1</a></li>
        <li><a data-toggle="tab" href="#lB">Week 2</a></li>
        <li><a data-toggle="tab" href="#lC">Week 3</a></li>
        <li><a data-toggle="tab" href="#lD">Week 4</a></li>
    </ul>
    <div class="tab-content span10 pull-right no-leftmargin">
        <div id="lA" class="span11 tab-pane active">
            <table class="table table-striped">
                <tbody>
                    <tr>
                        <td>1337799656</td>
                        <td>Info: Using the local log file 'arbiterd.log'</td>
                    </tr>
                    <tr>
                        <td>1337799656</td>
                        <td>Warning: I autogenerated some Arbiter modules, please look at your configuration</td>
                    </tr>
                    <tr>
                        <td>1337799656</td>
                        <td>Warning: I autogenerated some Arbiter modules, please look at your configuration</td>
                    </tr>
                    <tr>
                        <td>1337799656</td>
                        <td>Warning: I autogenerated some Arbiter modules, please look at your configuration</td>
                    </tr>
                    <tr>
                        <td>1337799656</td>
                        <td>Info: Using the local log file 'arbiterd.log'</td>
                    </tr>
                    <tr>
                        <td>1337799656</td>
                        <td>Warning: I autogenerated some Arbiter modules, please look at your configuration</td>
                    </tr>
                    <tr>
                        <td>1337799656</td>
                        <td>Warning: I autogenerated some Arbiter modules, please look at your configuration</td>
                    </tr>
                    <tr>
                        <td>1337799656</td>
                        <td>Warning: I autogenerated some Arbiter modules, please look at your configuration</td>
                    </tr>
                    <tr>
                        <td>1337799656</td>
                        <td>Info: Using the local log file 'arbiterd.log'</td>
                    </tr>
                    <tr>
                        <td>1337799656</td>
                        <td>Warning: I autogenerated some Arbiter modules, please look at your configuration</td>
                    </tr>
                    <tr>
                        <td>1337799656</td>
                        <td>Warning: I autogenerated some Arbiter modules, please look at your configuration</td>
                    </tr>
                    <tr>
                        <td>1337799656</td>
                        <td>Warning: I autogenerated some Arbiter modules, please look at your configuration</td>
                    </tr>
                </tbody>
            </table>
        </div>
        <div id="lB" class="span11 tab-pane">
            <table class="table table-striped">
                <tbody>
                    <tr>
                        <td>1337799656</td>
                        <td>Info: Using the local log file 'arbiterd.log'</td>
                    </tr>
                    <tr>
                        <td>1337799656</td>
                        <td>Warning: I autogenerated some Arbiter modules, please look at your configuration</td>
                    </tr>
                    <tr>
                        <td>1337799656</td>
                        <td>Warning: I autogenerated some Arbiter modules, please look at your configuration</td>
                    </tr>
                    <tr>
                        <td>1337799656</td>
                        <td>Warning: I autogenerated some Arbiter modules, please look at your configuration</td>
                    </tr>
                </tbody>
            </table>
        </div>
        <div id="lC" class="span11 tab-pane">
            <p>What up girl, this is Section C.</p>
        </div>
        <div id="lD" class="span11 tab-pane">
            <table class="table table-striped">
                <tbody>
                    <tr>
                        <td>1337799656</td>
                        <td>Info: Using the local log file 'arbiterd.log'</td>
                    </tr>
                    <tr>
                        <td>1337799656</td>
                        <td>Warning: I autogenerated some Arbiter modules, please look at your configuration</td>
                    </tr>
                    <tr>
                        <td>1337799656</td>
                        <td>Warning: I autogenerated some Arbiter modules, please look at your configuration</td>
                    </tr>
                    <tr>
                        <td>1337799656</td>
                        <td>Warning: I autogenerated some Arbiter modules, please look at your configuration</td>
                    </tr>
                </tbody>
            </table>
        </div>
    </div>
</div>
<div class="pagination pull-right">
    <ul>
        <li><a href="#">Prev</a></li>
        <li class="active"><a href="#">1</a></li>
        <li><a href="#">2</a></li>
        <li><a href="#">3</a></li>
        <li><a href="#">4</a></li>
        <li><a href="#">Next</a></li>
    </ul>
</div>
<!-- Log Contaier End -->